"""High-performance trading engine built with Rust and exposed via PyO3."""

from ._trading_engine import (
    Account,
    AssetConfig,
    Engine,
    LevelQuote,
    MarketDepth,
    MultiAssetMarketSim,
    Order,
    OrderStatus,
    OrderType,
    Position,
    RiskConfig,
    Side,
    TimeInForce,
    Trade,
)
from .kraken import (
    KrakenBookDelta,
    KrakenClient,
    KrakenMarketSession,
    KrakenOrderBookReplayer,
    KrakenTrade,
    KrakenWebSocketRecorder,
    normalize_kraken_rest_pair,
    normalize_kraken_ws_pair,
)

__all__ = [
    "Account",
    "AssetConfig",
    "Engine",
    "KrakenBookDelta",
    "KrakenClient",
    "KrakenMarketSession",
    "KrakenOrderBookReplayer",
    "KrakenTrade",
    "KrakenWebSocketRecorder",
    "LevelQuote",
    "MarketDepth",
    "MultiAssetMarketSim",
    "Order",
    "OrderStatus",
    "OrderType",
    "Position",
    "RiskConfig",
    "Side",
    "TimeInForce",
    "Trade",
    "normalize_kraken_rest_pair",
    "normalize_kraken_ws_pair",
]
